sudo: required
before_install: gem update --system
dist: trusty
language: ruby
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.0

after_success:
- bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: 3d676246ffa66d3fdef6253a9870431b1a2da04e9ecb25486c08a38823c37b6a
